package top.potmot.model.associations.oneToOne

const val mysqlResult = """
[(all-tables.sql, DROP TABLE IF EXISTS `O_O_TARGET`;
DROP TABLE IF EXISTS `O_O_SOURCE`;

CREATE TABLE `O_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE TABLE `O_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TARGET_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

ALTER TABLE `O_O_SOURCE`
    ADD CONSTRAINT `FK_ONE_TO_ONE`
        FOREIGN KEY (`TARGET_ID`)
            REFERENCES `O_O_TARGET` (`ID`);

), (o_o_source.sql, DROP TABLE IF EXISTS `O_O_SOURCE`;

CREATE TABLE `O_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TARGET_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

ALTER TABLE `O_O_SOURCE`
    ADD CONSTRAINT `FK_ONE_TO_ONE`
        FOREIGN KEY (`TARGET_ID`)
            REFERENCES `O_O_TARGET` (`ID`);

), (o_o_target.sql, DROP TABLE IF EXISTS `O_O_TARGET`;

CREATE TABLE `O_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

)]
"""

const val postgresResult = """
[(all-tables.sql, DROP TABLE IF EXISTS "O_O_TARGET" CASCADE;
DROP TABLE IF EXISTS "O_O_SOURCE" CASCADE;

CREATE TABLE "O_O_TARGET" (
    "ID" BIGSERIAL NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE "O_O_SOURCE" (
    "ID" BIGSERIAL NOT NULL,
    "TARGET_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "O_O_SOURCE"
    ADD CONSTRAINT "FK_ONE_TO_ONE"
        FOREIGN KEY ("TARGET_ID")
            REFERENCES "O_O_TARGET" ("ID");

), (o_o_source.sql, DROP TABLE IF EXISTS "O_O_SOURCE" CASCADE;

CREATE TABLE "O_O_SOURCE" (
    "ID" BIGSERIAL NOT NULL,
    "TARGET_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "O_O_SOURCE"
    ADD CONSTRAINT "FK_ONE_TO_ONE"
        FOREIGN KEY ("TARGET_ID")
            REFERENCES "O_O_TARGET" ("ID");

), (o_o_target.sql, DROP TABLE IF EXISTS "O_O_TARGET" CASCADE;

CREATE TABLE "O_O_TARGET" (
    "ID" BIGSERIAL NOT NULL,
    PRIMARY KEY ("ID")
);

)]
"""

const val h2Result = """
[(all-tables.sql, DROP TABLE IF EXISTS `O_O_TARGET` CASCADE;
DROP TABLE IF EXISTS `O_O_SOURCE` CASCADE;

CREATE TABLE `O_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `O_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TARGET_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `O_O_SOURCE`
    ADD CONSTRAINT `FK_ONE_TO_ONE`
        FOREIGN KEY (`TARGET_ID`)
            REFERENCES `O_O_TARGET` (`ID`);

), (o_o_source.sql, DROP TABLE IF EXISTS `O_O_SOURCE` CASCADE;

CREATE TABLE `O_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TARGET_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `O_O_SOURCE`
    ADD CONSTRAINT `FK_ONE_TO_ONE`
        FOREIGN KEY (`TARGET_ID`)
            REFERENCES `O_O_TARGET` (`ID`);

), (o_o_target.sql, DROP TABLE IF EXISTS `O_O_TARGET` CASCADE;

CREATE TABLE `O_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
);

)]
"""
