package top.potmot.enumeration

enum class GenerateTag {
    BackEnd,
    Table,
    Enum,
    Entity,
    DTO,
    Permission,
    Route,
    Service,
    FrontEnd,
    Component,
    EnumView,
    EnumSelect,
    EnumNullableSelect,
    IdSelect,
    IdMultiSelect,
    Page,
    AddForm,
    EditForm,
    EditTable,
    QueryForm,
    AddFormDataType,
    DefaultAddFormData,
    Rules,
    AddFormRules,
    EditFormRules,
    EditTableRules,
}
