spring:
  profiles:
    active: mysql
  liquibase:
    enabled: false

logging:
  level:
    top.potmot: info

jimmer:
  language: kotlin
  default-batch-size: 128
  default-list-batch-size: 128
  client:
    ts:
      path: /ts.zip
  show-sql: on
  pretty-sql: true
  id-only-target-checking-level: ALL
  database-validation:
    mode: ERROR
    schema: jimmer_code_gen
  default-enum-strategy: NAME

# 代码生成
gen:
  language: kotlin
  table-prefix: t_,gen_
  table-suffix:
  table-comment-prefix:
  table-comment-suffix: 表
  column-prefix:
  column-suffix:
  column-comment-prefix:
  column-comment-suffix:
