spring:
  profiles:
    active: h2

  liquibase:
    enabled: false

  web:
    resources:
      static-locations: classpath:/dist

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    top.potmot: info

jimmer:
  language: kotlin
  default-batch-size: 128
  default-list-batch-size: 128

  id-only-target-checking-level: ALL
  database-validation:
    mode: ERROR
  default-enum-strategy: NAME

  client:
    ts:
      path: /ts.zip
      mutable: true

  show-sql: true
  pretty-sql: true
  inline-sql-variables: true


# 代码生成
jimmer-code-gen:
  language: kotlin
  table-name-prefixes: t_
  table-name-suffixes:
  table-comment-prefixes:
  table-comment-suffixes: 表
  column-name-prefixes:
  column-name-suffixes:
  column-comment-prefixes:
  column-comment-suffixes:
