logging:
  level:
    top.potmot: info

spring:
  profiles:
    active: postgresql

  jackson:
    # 格式化全局时间属性
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8

jimmer:
  language: kotlin
  default-batch-size: 128
  default-list-batch-size: 128
  client:
    ts:
      path: /ts.zip
  show-sql: on
  pretty-sql: true
  id-only-target-checking-level: ALL
  database-validation:
    mode: ERROR
    schema: jimmer_code_gen

# 代码生成
gen:
  # 作者
  # author:
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: gen_, t_
  removeTablePrefix: false
  tableSuffix: model, info
  removeTableSuffix: false
  columnPrefix: gen_
  removeColumnPrefix: true
  columnSuffix:
  removeColumnSuffix: true
  language: kotlin
