spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect

jimmer-code-gen:
  dataSourceType: postgresql
