spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/jimmer_code_gen?serverTimezone=Asia/Shanghai
    username: root
    password: root

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect

gen:
  dataSourceType: mysql
