logging:
  level:
    top.potmot: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/jimmer-code-gen?serverTimezone=Asia/Shanghai
  jackson:
    # 格式化全局时间属性
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8

jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  default-batch-size: 128
  default-list-batch-size: 128
  client:
    ts:
      path: /ts.zip
  show-sql: on
  pretty-sql: true

# 代码生成
gen:
  # 作者
  # author:
  # 默认生成包路径 system 需改成自己的模块名称
  # packageName: com.example
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: gen, t
  tableSuffix: model, info
  language: kotlin
