spring:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3307/jimmer-code-gen?serverTimezone=Asia/Shanghai
    gen:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3307/ry-vue?serverTimezone=Asia/Shanghai

jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  default-batch-size: 128
  default-list-batch-size: 128
  client:
    ts:
      path: /ts
  show-sql: on
  pretty-sql: on

# 代码生成
gen:
  # 作者
  # author:
  # 默认生成包路径 system 需改成自己的模块名称
  # packageName: com.example
  # 自动去除表前缀，默认是true
  # autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  # tablePrefix: t_
  # language: java
