spring:
  profiles:
    active: h2

  liquibase:
    enabled: false

  web:
    resources:
      static-locations: classpath:/dist

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    top.potmot: info

jimmer:
  language: kotlin
  default-batch-size: 128
  default-list-batch-size: 128
  client:
    ts:
      path: /ts.zip
      mutable: true
  show-sql: on
  pretty-sql: true
  id-only-target-checking-level: ALL
  database-validation:
    mode: ERROR
    schema: jimmer_code_gen
  default-enum-strategy: NAME

# 代码生成
gen:
  language: kotlin
  table-name-prefixes: t_,gen_
  table-name-suffixes:
  table-comment-prefixes:
  table-comment-suffixes: 表
  column-name-prefixes:
  column-name-suffixes:
  column-comment-prefixes:
  column-comment-suffixes:
