package top.potmot.model.longNames

const val mysqlLowerResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3`;

CREATE TABLE `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` (
    `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` BIGINT NOT NULL AUTO_INCREMENT,
    `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e82` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE UNIQUE INDEX `uidx_first_column` ON `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` (`sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e82`);
CREATE INDEX `idx_multi_columns` ON `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` (`sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3`, `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e82`);

), (ddl/sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.sql, DROP TABLE IF EXISTS `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3`;

CREATE TABLE `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` (
    `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` BIGINT NOT NULL AUTO_INCREMENT,
    `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e82` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE UNIQUE INDEX `uidx_first_column` ON `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` (`sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e82`);
CREATE INDEX `idx_multi_columns` ON `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3` (`sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b3`, `sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e82`);

)]
"""

const val mysqlUpperResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3`;

CREATE TABLE `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` (
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` BIGINT NOT NULL AUTO_INCREMENT,
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E82` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE UNIQUE INDEX `UIDX_FIRST_COLUMN` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E82`);
CREATE INDEX `IDX_MULTI_COLUMNS` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3`, `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E82`);

), (ddl/sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.sql, DROP TABLE IF EXISTS `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3`;

CREATE TABLE `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` (
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` BIGINT NOT NULL AUTO_INCREMENT,
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E82` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE UNIQUE INDEX `UIDX_FIRST_COLUMN` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E82`);
CREATE INDEX `IDX_MULTI_COLUMNS` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B3`, `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E82`);

)]
"""

const val postgresLowerResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" CASCADE;

CREATE TABLE "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" (
    "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" BIGSERIAL NOT NULL,
    "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e8" TEXT NOT NULL,
    PRIMARY KEY ("sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b")
);

CREATE UNIQUE INDEX "uidx_first_column" ON "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" ("sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e8");
CREATE INDEX "idx_multi_columns" ON "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" ("sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b", "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e8");

), (ddl/sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.sql, DROP TABLE IF EXISTS "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" CASCADE;

CREATE TABLE "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" (
    "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" BIGSERIAL NOT NULL,
    "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e8" TEXT NOT NULL,
    PRIMARY KEY ("sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b")
);

CREATE UNIQUE INDEX "uidx_first_column" ON "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" ("sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e8");
CREATE INDEX "idx_multi_columns" ON "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b" ("sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_bb0d4d2b", "sdaadsdassdddddddddddddddddddddddddddddddddddddddddddd_d409b7e8");

)]
"""

const val postgresUpperResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" CASCADE;

CREATE TABLE "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" (
    "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" BIGSERIAL NOT NULL,
    "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E8" TEXT NOT NULL,
    PRIMARY KEY ("SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B")
);

CREATE UNIQUE INDEX "UIDX_FIRST_COLUMN" ON "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" ("SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E8");
CREATE INDEX "IDX_MULTI_COLUMNS" ON "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" ("SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B", "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E8");

), (ddl/sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.sql, DROP TABLE IF EXISTS "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" CASCADE;

CREATE TABLE "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" (
    "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" BIGSERIAL NOT NULL,
    "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E8" TEXT NOT NULL,
    PRIMARY KEY ("SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B")
);

CREATE UNIQUE INDEX "UIDX_FIRST_COLUMN" ON "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" ("SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E8");
CREATE INDEX "IDX_MULTI_COLUMNS" ON "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B" ("SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_BB0D4D2B", "SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD_D409B7E8");

)]
"""

const val h2LowerCaseResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` CASCADE;

CREATE TABLE `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` (
    `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` BIGINT NOT NULL AUTO_INCREMENT,
    `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1` CHARACTER VARYING(500) NOT NULL,
    PRIMARY KEY (`sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd`)
);

CREATE UNIQUE INDEX `uidx_first_column` ON `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` (`sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1`);
CREATE INDEX `idx_multi_columns` ON `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` (`sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd`, `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1`);

), (ddl/sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.sql, DROP TABLE IF EXISTS `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` CASCADE;

CREATE TABLE `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` (
    `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` BIGINT NOT NULL AUTO_INCREMENT,
    `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1` CHARACTER VARYING(500) NOT NULL,
    PRIMARY KEY (`sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd`)
);

CREATE UNIQUE INDEX `uidx_first_column` ON `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` (`sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1`);
CREATE INDEX `idx_multi_columns` ON `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd` (`sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd`, `sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1`);

)]
"""

const val h2UpperCaseResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` CASCADE;

CREATE TABLE `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` (
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` BIGINT NOT NULL AUTO_INCREMENT,
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1` CHARACTER VARYING(500) NOT NULL,
    PRIMARY KEY (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD`)
);

CREATE UNIQUE INDEX `UIDX_FIRST_COLUMN` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1`);
CREATE INDEX `IDX_MULTI_COLUMNS` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD`, `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1`);

), (ddl/sdaadsdassddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.sql, DROP TABLE IF EXISTS `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` CASCADE;

CREATE TABLE `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` (
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` BIGINT NOT NULL AUTO_INCREMENT,
    `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1` CHARACTER VARYING(500) NOT NULL,
    PRIMARY KEY (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD`)
);

CREATE UNIQUE INDEX `UIDX_FIRST_COLUMN` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1`);
CREATE INDEX `IDX_MULTI_COLUMNS` ON `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD` (`SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD`, `SDAADSDASSDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1`);

)]
"""
