package top.potmot.model.associations.reversedOneToOne

const val mysqlResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS `USER_DETAIL`;
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER_DETAIL` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE TABLE `USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

ALTER TABLE `USER`
    ADD CONSTRAINT `FK_DETAIL_USER`
        FOREIGN KEY (`ID`)
            REFERENCES `USER_DETAIL` (`USER_ID`);

), (ddl/user.sql, DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

ALTER TABLE `USER`
    ADD CONSTRAINT `FK_DETAIL_USER`
        FOREIGN KEY (`ID`)
            REFERENCES `USER_DETAIL` (`USER_ID`);

), (ddl/user_detail.sql, DROP TABLE IF EXISTS `USER_DETAIL`;

CREATE TABLE `USER_DETAIL` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

)]
"""

const val postgresResult = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS "USER_DETAIL" CASCADE;
DROP TABLE IF EXISTS "USER" CASCADE;

CREATE TABLE "USER_DETAIL" (
    "ID" BIGSERIAL NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE "USER" (
    "ID" BIGSERIAL NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "USER"
    ADD CONSTRAINT "FK_DETAIL_USER"
        FOREIGN KEY ("ID")
            REFERENCES "USER_DETAIL" ("USER_ID");

), (ddl/user.sql, DROP TABLE IF EXISTS "USER" CASCADE;

CREATE TABLE "USER" (
    "ID" BIGSERIAL NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "USER"
    ADD CONSTRAINT "FK_DETAIL_USER"
        FOREIGN KEY ("ID")
            REFERENCES "USER_DETAIL" ("USER_ID");

), (ddl/user_detail.sql, DROP TABLE IF EXISTS "USER_DETAIL" CASCADE;

CREATE TABLE "USER_DETAIL" (
    "ID" BIGSERIAL NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

)]
"""

const val h2Result = """
[(ddl/all-tables.sql, DROP TABLE IF EXISTS `USER_DETAIL` CASCADE;
DROP TABLE IF EXISTS `USER` CASCADE;

CREATE TABLE `USER_DETAIL` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `USER`
    ADD CONSTRAINT `FK_DETAIL_USER`
        FOREIGN KEY (`ID`)
            REFERENCES `USER_DETAIL` (`USER_ID`);

), (ddl/user.sql, DROP TABLE IF EXISTS `USER` CASCADE;

CREATE TABLE `USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `USER`
    ADD CONSTRAINT `FK_DETAIL_USER`
        FOREIGN KEY (`ID`)
            REFERENCES `USER_DETAIL` (`USER_ID`);

), (ddl/user_detail.sql, DROP TABLE IF EXISTS `USER_DETAIL` CASCADE;

CREATE TABLE `USER_DETAIL` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

)]
"""
