package top.potmot.error

import org.babyfish.jimmer.error.ErrorFamily

@ErrorFamily
enum class ValidErrorCode {
    DUPLICATE_TABLE_NAME,

    DUPLICATE_ASSOCIATION_NAME,

    DUPLICATE_FOREIGN_KEY_NAME,

    DUPLICATE_COLUMN_NAME,

    DUPLICATE_INDEX_REF_COLUMN,

    COLUMN_CATEGORY_ILLEGAL,

    DUPLICATE_INDEX_NAME,

    DUPLICATE_ENTITY_NAME,

    DUPLICATE_ENUM_NAME,

    DUPLICATE_ENUM_ITEMS,

    DUPLICATE_PROPERTY_NAME,

    TO_MANY_SAVE_REQUIRED_KEY,

    SELF_ASSOCIATION_CIRCULAR_DEPENDENCE,
}