package top.potmot.model.associations.manyToOne

const val mysqlResult = """
[(all-tables.sql, DROP TABLE IF EXISTS `M_O_SOURCE`;
DROP TABLE IF EXISTS `M_O_TARGET`;

CREATE TABLE `M_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SOURCE_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

CREATE TABLE `M_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

ALTER TABLE `M_O_SOURCE`
    ADD CONSTRAINT `FK_MANY_TO_ONE`
        FOREIGN KEY (`SOURCE_ID`)
            REFERENCES `M_O_TARGET` (`ID`);

), (m_o_source.sql, DROP TABLE IF EXISTS `M_O_SOURCE`;

CREATE TABLE `M_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SOURCE_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

ALTER TABLE `M_O_SOURCE`
    ADD CONSTRAINT `FK_MANY_TO_ONE`
        FOREIGN KEY (`SOURCE_ID`)
            REFERENCES `M_O_TARGET` (`ID`);

), (m_o_target.sql, DROP TABLE IF EXISTS `M_O_TARGET`;

CREATE TABLE `M_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  CHARACTER SET = utf8mb4
  COMMENT = ''
  ROW_FORMAT = Dynamic;

)]
"""

const val postgresResult = """
[(all-tables.sql, DROP TABLE IF EXISTS "M_O_SOURCE" CASCADE;
DROP TABLE IF EXISTS "M_O_TARGET" CASCADE;

CREATE TABLE "M_O_SOURCE" (
    "ID" BIGSERIAL NOT NULL,
    "SOURCE_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE "M_O_TARGET" (
    "ID" BIGSERIAL NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "M_O_SOURCE"
    ADD CONSTRAINT "FK_MANY_TO_ONE"
        FOREIGN KEY ("SOURCE_ID")
            REFERENCES "M_O_TARGET" ("ID");

), (m_o_source.sql, DROP TABLE IF EXISTS "M_O_SOURCE" CASCADE;

CREATE TABLE "M_O_SOURCE" (
    "ID" BIGSERIAL NOT NULL,
    "SOURCE_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "M_O_SOURCE"
    ADD CONSTRAINT "FK_MANY_TO_ONE"
        FOREIGN KEY ("SOURCE_ID")
            REFERENCES "M_O_TARGET" ("ID");

), (m_o_target.sql, DROP TABLE IF EXISTS "M_O_TARGET" CASCADE;

CREATE TABLE "M_O_TARGET" (
    "ID" BIGSERIAL NOT NULL,
    PRIMARY KEY ("ID")
);

)]
"""

const val h2Result = """
[(all-tables.sql, DROP TABLE IF EXISTS `M_O_SOURCE` CASCADE;
DROP TABLE IF EXISTS `M_O_TARGET` CASCADE;

CREATE TABLE `M_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SOURCE_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `M_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `M_O_SOURCE`
    ADD CONSTRAINT `FK_MANY_TO_ONE`
        FOREIGN KEY (`SOURCE_ID`)
            REFERENCES `M_O_TARGET` (`ID`);

), (m_o_source.sql, DROP TABLE IF EXISTS `M_O_SOURCE` CASCADE;

CREATE TABLE `M_O_SOURCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SOURCE_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `M_O_SOURCE`
    ADD CONSTRAINT `FK_MANY_TO_ONE`
        FOREIGN KEY (`SOURCE_ID`)
            REFERENCES `M_O_TARGET` (`ID`);

), (m_o_target.sql, DROP TABLE IF EXISTS `M_O_TARGET` CASCADE;

CREATE TABLE `M_O_TARGET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
);

)]
"""
