import type { QueryType, SortDirection } from '../enums';

export type GenTableDto = {
    'NodeSet/TABLE': {
        readonly id: number, 
        readonly tableName: string, 
        readonly tableComment: string, 
        readonly tableType: string, 
        readonly createdTime: string, 
        readonly modifiedTime: string
    }, 
    'NodeSet/TABLE_COMPLEX': {
        readonly id: number, 
        readonly tableName: string, 
        readonly tableComment: string, 
        readonly tableType: string, 
        readonly createdTime: string, 
        readonly modifiedTime: string, 
        readonly remark: string, 
        readonly columns: ReadonlyArray<{
            readonly id: number, 
            readonly columnSort: number, 
            readonly columnName: string, 
            readonly columnType: string, 
            readonly columnDisplaySize: number, 
            readonly columnPrecision: number, 
            readonly columnDefault: string, 
            readonly columnComment: string, 
            readonly isPk: boolean, 
            readonly isAutoIncrement: boolean, 
            readonly isUnique: boolean, 
            readonly isNotNull: boolean, 
            readonly isVirtualColumn: boolean
        }>
    }, 
    'NodeSet/CLASS': {
        readonly id: number, 
        readonly className: string, 
        readonly classComment: string, 
        readonly packageName: string, 
        readonly moduleName: string, 
        readonly functionName: string, 
        readonly author: string, 
        readonly genPath: string, 
        readonly isAdd: boolean, 
        readonly isEdit: boolean, 
        readonly isList: boolean, 
        readonly isQuery: boolean, 
        readonly orderKey: number, 
        readonly createdTime: string, 
        readonly modifiedTime: string
    }, 
    'NodeSet/CLASS_COMPLEX': {
        readonly id: number, 
        readonly className: string, 
        readonly classComment: string, 
        readonly packageName: string, 
        readonly moduleName: string, 
        readonly functionName: string, 
        readonly author: string, 
        readonly genPath: string, 
        readonly isAdd: boolean, 
        readonly isEdit: boolean, 
        readonly isList: boolean, 
        readonly isQuery: boolean, 
        readonly orderKey: number, 
        readonly createdTime: string, 
        readonly modifiedTime: string, 
        readonly remark: string, 
        readonly columns: ReadonlyArray<{
            readonly id: number, 
            readonly fieldName: string, 
            readonly fieldType: string, 
            readonly fieldComment: string, 
            readonly isList: boolean, 
            readonly listSort: number, 
            readonly isAdd: boolean, 
            readonly addSort: number, 
            readonly isAddRequired: boolean, 
            readonly isEdit: boolean, 
            readonly editSort: number, 
            readonly isEditRequired: boolean, 
            readonly readOnly: boolean, 
            readonly isQuery: boolean, 
            readonly querySort: number, 
            readonly queryType: QueryType, 
            readonly dictType: string, 
            readonly isSort: boolean, 
            readonly sortDirection: SortDirection, 
            readonly isLogicalDelete: boolean
        }>
    }, 
    'NodeSet/COMMON': {
        readonly id: number, 
        readonly createdTime: string, 
        readonly modifiedTime: string, 
        readonly remark: string, 
        readonly tableName: string, 
        readonly tableComment: string, 
        readonly tableType: string, 
        readonly className: string, 
        readonly classComment: string, 
        readonly packageName: string, 
        readonly moduleName: string, 
        readonly functionName: string, 
        readonly author: string, 
        readonly genPath: string, 
        readonly isAdd: boolean, 
        readonly isEdit: boolean, 
        readonly isList: boolean, 
        readonly isQuery: boolean, 
        readonly orderKey: number
    }, 
    'NodeSet/COMPLEX': {
        readonly id: number, 
        readonly createdTime: string, 
        readonly modifiedTime: string, 
        readonly remark: string, 
        readonly tableName: string, 
        readonly tableComment: string, 
        readonly tableType: string, 
        readonly className: string, 
        readonly classComment: string, 
        readonly packageName: string, 
        readonly moduleName: string, 
        readonly functionName: string, 
        readonly author: string, 
        readonly genPath: string, 
        readonly isAdd: boolean, 
        readonly isEdit: boolean, 
        readonly isList: boolean, 
        readonly isQuery: boolean, 
        readonly orderKey: number, 
        readonly columns: ReadonlyArray<{
            readonly id: number, 
            readonly table: {readonly id: number}, 
            readonly columnSort: number, 
            readonly columnName: string, 
            readonly columnTypeCode: number, 
            readonly columnType: string, 
            readonly columnDisplaySize: number, 
            readonly columnPrecision: number, 
            readonly columnDefault: string, 
            readonly columnComment: string, 
            readonly isPk: boolean, 
            readonly isAutoIncrement: boolean, 
            readonly isUnique: boolean, 
            readonly isNotNull: boolean, 
            readonly isVirtualColumn: boolean, 
            readonly fieldName: string, 
            readonly fieldType: string, 
            readonly fieldComment: string, 
            readonly isList: boolean, 
            readonly listSort: number, 
            readonly isAdd: boolean, 
            readonly addSort: number, 
            readonly isAddRequired: boolean, 
            readonly isEdit: boolean, 
            readonly editSort: number, 
            readonly isEditRequired: boolean, 
            readonly readOnly: boolean, 
            readonly isQuery: boolean, 
            readonly querySort: number, 
            readonly queryType: QueryType, 
            readonly dictType: string, 
            readonly isSort: boolean, 
            readonly sortDirection: SortDirection, 
            readonly isLogicalDelete: boolean
        }>
    }
}