/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElTree: typeof import('element-plus/es')['ElTree']
    ERMapping: typeof import('./src/components/ERMapping.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableGroupList: typeof import('./src/components/tableMenu/TableGroupList.vue')['default']
    TableGroupMenu: typeof import('./src/components/tableMenu/TableGroupMenu.vue')['default']
    TableGroupTree: typeof import('./src/components/tableMenu/TableGroupTree.vue')['default']
    TableGroupTreeItem: typeof import('./src/components/tableMenu/TableGroupTreeItem.vue')['default']
    TableInfo: typeof import('./src/components/TableInfo.vue')['default']
    TableMapping: typeof import('./src/components/TableMapping.vue')['default']
  }
}
