package top.potmot.model.dto

typealias GenPropertyView = GenEntityPropertiesView.TargetOf_properties

typealias PropertyEnum = GenEntityPropertiesView.TargetOf_properties.TargetOf_enum

typealias PropertyEnumItem = GenEntityPropertiesView.TargetOf_properties.TargetOf_enum.TargetOf_items
